 With 
    target_device_data  as (
  /* get devicerecords for parsing  */
    Select 
        d.device_pk
        ,d.name device_name
        ,split_part(d.name,'.',1) hostname
        ,split_part(d.name,'.',3) dom
        ,split_part(d.name,'.',2) loc       
    From view_device_v2 d
    Left Join view_containerinstance_v1 coi ON coi.device_fk = d.device_pk
    Where d.network_device = 'f' 
        and coi.container_id is Null    /* remove network devices and containers */
        and lower(d.type) Not IN ('cluster','unknown')
        and split_part(d.name,'.',3) = 'five9lab'
        and (position('pm' IN lower(d.name))= 1 or position('qa' IN lower(d.name))= 1 or position('dev' IN lower(d.name))= 1 or position('tag' IN lower(d.name))= 1)
        and (position('_old' IN lower(d.name))= 0 and position('labcom' IN lower(d.name))= 0 and position('new.' IN lower(d.name))= 0)
    ),
    parse_data  as (
  /* parse env, product, index, farm   */
    Select 
        tdd.*
        ,Case When position('qa' IN lower(tdd.hostname))> 0 Then 'qa'
            When position('dev' IN lower(tdd.hostname))> 0 Then 'dev'
            When position('pm' IN lower(tdd.hostname))> 0 Then 'pm'
            When position('tag' IN lower(tdd.hostname))> 0 Then 'tag'
            Else 'unk'
        End env
        ,Case When position('core' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('env' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('envws' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('ftp' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('ftpr' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('ftpnas' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('aero' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('api' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('apife' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('apiewbe' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('apiewfe' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('apilb' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('ts' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('bil' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('cp' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('cplb' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('cdntr' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('dsb' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('db' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('grdb' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('maindbm' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('maindbs' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('maindb' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('relaydb' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('sipdb' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('loginbe' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('loginlb' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('cpnas' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('nas' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('lb' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('nss' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('rmq' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('rpt' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('sat' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('sum' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('sip' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('tts' IN lower(tdd.hostname)) > 0 Then 'VCC'
When position('app' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('vcc' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('stat' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('rmq' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('aerosup' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('aero' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('auth' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('dsbfrm' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('solr' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('zk' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('stream' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('chat' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('hzc' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('sup' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('web' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('ws' IN lower(tdd.hostname)) > 0 Then 'Freedom'
When position('app' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('ws' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('db' IN lower(tdd.hostname)) > 0 and position('scc' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('pdb' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('svc' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('fdmsync' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('nas' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('rpt' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('sync' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('social' IN lower(tdd.hostname)) > 0 Then 'SCC'
When position('amd' IN lower(tdd.hostname)) > 0 Then 'FVS'
When position('vdb' IN lower(tdd.hostname)) > 0 Then 'FVS'
When position('nss' IN lower(tdd.hostname)) > 0 Then 'FVS'
When position('siplb' IN lower(tdd.hostname)) > 0 Then 'FVS'
When position('sip' IN lower(tdd.hostname)) > 0 Then 'FVS'
When position('vms' IN lower(tdd.hostname)) > 0 Then 'FVS'
When position('vacs' IN lower(tdd.hostname)) > 0 Then 'FVS'
When position('kafka' IN lower(tdd.hostname)) > 0 Then 'SFGW'
When position('kafkazk' IN lower(tdd.hostname)) > 0 Then 'SFGW'
When position('zk' IN lower(tdd.hostname)) > 0 Then 'SFGW'
When position('sfgw' IN lower(tdd.hostname)) > 0 Then 'SFGW'
When position('db' IN lower(tdd.hostname)) > 0 and position('vrnt' IN lower(tdd.hostname)) > 0 Then 'Verint'
When position('omnitext' IN lower(tdd.hostname)) > 0 Then 'Verint'
When position('siprecmon' IN lower(tdd.hostname)) > 0 Then 'Verint'
When position('pxy' IN lower(tdd.hostname)) > 0 Then 'Verint'
When position('sync' IN lower(tdd.hostname)) > 0 Then 'Verint'
            Else 'No Known Product'
        End product
        ,Case When position('core' IN lower(tdd.hostname)) > 0 Then 'core'
When position('env' IN lower(tdd.hostname)) > 0 Then 'env'
When position('envws' IN lower(tdd.hostname)) > 0 Then 'envws'
When position('ftp' IN lower(tdd.hostname)) > 0 Then 'ftp'
When position('ftpr' IN lower(tdd.hostname)) > 0 Then 'ftpr'
When position('ftpnas' IN lower(tdd.hostname)) > 0 Then 'ftpnas'
When position('aero' IN lower(tdd.hostname)) > 0 Then 'aero'
When position('api' IN lower(tdd.hostname)) > 0 Then 'api'
When position('apife' IN lower(tdd.hostname)) > 0 Then 'apife'
When position('apiewbe' IN lower(tdd.hostname)) > 0 Then 'apiebe'
When position('apiewfe' IN lower(tdd.hostname)) > 0 Then 'apiewfe'
When position('apilb' IN lower(tdd.hostname)) > 0 Then 'apilb'
When position('ts' IN lower(tdd.hostname)) > 0 Then 'ts'
When position('bil' IN lower(tdd.hostname)) > 0 Then 'bil'
When position('cp' IN lower(tdd.hostname)) > 0 Then 'cp'
When position('cplb' IN lower(tdd.hostname)) > 0 Then 'cplb'
When position('cdntr' IN lower(tdd.hostname)) > 0 Then 'cdntr'
When position('dsb' IN lower(tdd.hostname)) > 0 Then 'dsb'
When position('db' IN lower(tdd.hostname)) > 0 Then 'db'
When position('grdb' IN lower(tdd.hostname)) > 0 Then 'grdb'
When position('maindbm' IN lower(tdd.hostname)) > 0 Then 'maindbm'
When position('maindbs' IN lower(tdd.hostname)) > 0 Then 'maindbs'
When position('maindb' IN lower(tdd.hostname)) > 0 Then 'maindb'
When position('relaydb' IN lower(tdd.hostname)) > 0 Then 'relaydb'
When position('sipdb' IN lower(tdd.hostname)) > 0 Then 'sipdb'
When position('loginbe' IN lower(tdd.hostname)) > 0 Then 'loginbe'
When position('loginlb' IN lower(tdd.hostname)) > 0 Then 'loginlb'
When position('cpnas' IN lower(tdd.hostname)) > 0 Then 'cpnas'
When position('nas' IN lower(tdd.hostname)) > 0 Then 'nas'
When position('lb' IN lower(tdd.hostname)) > 0 Then 'lb'
When position('nss' IN lower(tdd.hostname)) > 0 Then 'nss'
When position('rmq' IN lower(tdd.hostname)) > 0 Then 'rmq'
When position('rpt' IN lower(tdd.hostname)) > 0 Then 'rpt'
When position('sat' IN lower(tdd.hostname)) > 0 Then 'sat'
When position('sum' IN lower(tdd.hostname)) > 0 Then 'sum'
When position('sip' IN lower(tdd.hostname)) > 0 Then 'sip'
When position('tts' IN lower(tdd.hostname)) > 0 Then 'tts'
When position('app' IN lower(tdd.hostname)) > 0 Then 'app'
When position('vcc' IN lower(tdd.hostname)) > 0 Then 'vcc'
When position('stat' IN lower(tdd.hostname)) > 0 Then 'stat'
When position('rmq' IN lower(tdd.hostname)) > 0 Then 'rmq'
When position('aerosup' IN lower(tdd.hostname)) > 0 Then 'aerosup'
When position('aero' IN lower(tdd.hostname)) > 0 Then 'aero'
When position('auth' IN lower(tdd.hostname)) > 0 Then 'auth'
When position('dsbfrm' IN lower(tdd.hostname)) > 0 Then 'dsbfrm'
When position('solr' IN lower(tdd.hostname)) > 0 Then 'solr'
When position('zk' IN lower(tdd.hostname)) > 0 Then 'zk'
When position('stream' IN lower(tdd.hostname)) > 0 Then 'stream'
When position('chat' IN lower(tdd.hostname)) > 0 Then 'chat'
When position('hzc' IN lower(tdd.hostname)) > 0 Then 'hzc'
When position('sup' IN lower(tdd.hostname)) > 0 Then 'sup'
When position('web' IN lower(tdd.hostname)) > 0 Then 'web'
When position('ws' IN lower(tdd.hostname)) > 0 Then 'ws'
When position('app' IN lower(tdd.hostname)) > 0 Then 'app'
When position('ws' IN lower(tdd.hostname)) > 0 Then 'ws'
When position('pdb' IN lower(tdd.hostname)) > 0 Then 'pdb'
When position('svc' IN lower(tdd.hostname)) > 0 Then 'svc'
When position('fdmsync' IN lower(tdd.hostname)) > 0 Then 'fdmsync'
When position('nas' IN lower(tdd.hostname)) > 0 Then 'nas'
When position('rpt' IN lower(tdd.hostname)) > 0 Then 'rpt'
When position('sync' IN lower(tdd.hostname)) > 0 Then 'sync'
When position('social' IN lower(tdd.hostname)) > 0 Then 'social'
When position('amd' IN lower(tdd.hostname)) > 0 Then 'amd'
When position('vdb' IN lower(tdd.hostname)) > 0 Then 'vdb'
When position('nss' IN lower(tdd.hostname)) > 0 Then 'nss'
When position('siplb' IN lower(tdd.hostname)) > 0 Then 'siplb'
When position('sip' IN lower(tdd.hostname)) > 0 Then 'sip'
When position('vms' IN lower(tdd.hostname)) > 0 Then 'vms'
When position('vacs' IN lower(tdd.hostname)) > 0 Then 'vacs'
When position('kafka' IN lower(tdd.hostname)) > 0 Then 'kafka'
When position('kafkazk' IN lower(tdd.hostname)) > 0 Then 'kafkazk'
When position('zk' IN lower(tdd.hostname)) > 0 Then 'zk'
When position('sfgw' IN lower(tdd.hostname)) > 0 Then 'sfgw'
When position('omnitext' IN lower(tdd.hostname)) > 0 Then 'omnitext'
When position('siprecmon' IN lower(tdd.hostname)) > 0 Then 'siprecmon'
When position('pxy' IN lower(tdd.hostname)) > 0 Then 'pxy'
When position('sync' IN lower(tdd.hostname)) > 0 Then 'sync'
            Else 'No Known Role'
        End roles
        ,Case When right(lower(tdd.hostname),1) >= '0' and right(lower(tdd.hostname),1) <= '9' Then right(lower(tdd.hostname),3)
            Else left(right(lower(tdd.hostname),4),3)
        End index1
        ,Case When right(lower(tdd.hostname),1)>= '0' and right(lower(tdd.hostname),1) <= '9' Then ''
            Else right(lower(tdd.hostname),1)
        End farm        
    From target_device_data tdd
/*    Where position('frm' IN lower(tdd.hostname)) > 0 or position('fdm' IN lower(tdd.hostname)) > 0 or position('fds' IN lower(tdd.hostname)) > 0 or position('ftp' IN lower(tdd.hostname)) > 0
          or position('sip' IN lower(tdd.hostname)) > 0 or position('scc' IN lower(tdd.hostname)) > 0 or position('vcc' IN lower(tdd.hostname)) > 0 or position('tts' IN lower(tdd.hostname)) > 0
          or position('solr' IN lower(tdd.hostname)) > 0 or position('sfgw' IN lower(tdd.hostname)) > 0 or position('social' IN lower(tdd.hostname)) > 0     */
    )
    Select * from parse_data pd
    Order by product, env, loc, roles, index1, farm